blank_issues_enabled: true
contact_links:
  - name: 提问、求助、好想法
    url: https://github.com/orgs/zotero-chinese/discussions/new/choose
    about: "前往 Discussion 参与讨论！"

  - name: QQ 群
    url: https://zotero-chinese.com/contributing/#参与讨论
    about: "在链接中查看 QQ 群号码"
